---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
    cleanupOnFail: true
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: jacobalberty/unifi
              tag: v8.1.113
        pod:
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      main:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${MLB_UNIFI_ADDR}"
          metallb.universe.tf/allow-shared-ip: unifi
        ports:
          http:
            port: 8443
            enabled: true
            protocol: HTTPS
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host "unifi.${MAIN_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
                  pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: unifi-config-v4
        globalMounts:
          - path: "/unifi"