---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config-v1
  namespace: networking
  labels:
    app.kubernetes.io/name: &name unifi
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
