---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: z2m
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  dependsOn:
    - name: mosquitto
      namespace: home
    - name: csi-driver-nfs2
      namespace: storage
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.32.2

    env:
      TZ: Europe/Helsinki
      ZIGBEE2MQTT_DATA: /data
      ZIGBEE2MQTT_CONFIG_MQTT_USER:
        valueFrom:
          secretKeyRef:
            name: mosquitto-secret
            key: username
      ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: mosquitto-secret
            key: password
      ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID:
        valueFrom:
          secretKeyRef:
            name: z2m-secret
            key: pan_id
      ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "true"
      ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601_local
      ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
      ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "true"
      ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info
      ZIGBEE2MQTT_CONFIG_AVAILABILITY_: "true"
      ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
      ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: &port 8082
      ZIGBEE2MQTT_CONFIG_FRONTEND_URL: "https://zigbee.${MAIN_DOMAIN}"
      ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
      ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://${SVC_MQTT_ADDR}"
      ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: "zigbee2mqtt"
      ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
      ZIGBEE2MQTT_CONFIG_SERIAL_PORT: tcp://10.0.60.2:6638

    service:
      main:
        ports:
          http:
            port: 8082

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
          nginx.ingress.kubernetes.io/auth-realm: "Authentication required"
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "z2m.${MAIN_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: z2m-config-v4
        mountPath: "/data"

    tolerations:
      - key: "master"
        operator: "Equal"
        value: "false"
        effect: "NoSchedule"
