---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: z2m-config-v4
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client-bgp
