apiVersion: v1
kind: Secret
metadata:
    name: z2m-secret
    namespace: home
type: Opaque
stringData:
    pan_id: ENC[AES256_GCM,data:nkB0og==,iv:gps9i1XP3sXZ3/npCd43oaWzUrWFv+IJHHQYOtltCVA=,tag:eak5rVK/ZsBCv3y3Xj+NrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwnsn3k525nltu06qtjhjrk37zffucrnygv6p6akdztjhlcm5qwqwqgpjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVnM3L1Zzak5yMjJ3MUxk
            Mk5HZFVkTGl5T2JwS0dNWHV6TlBkblFrenhZClU5azM1OC9qVkdmbXQzbCsycG1L
            ZndqUFBPNWJvRE9VeGRGaGRqLy9BYnMKLS0tIFE2MkdEYnVWSFkyYnRZZFo3QVh2
            eUM4WjZiaCtKYW9TRjZYYlU2MXhQZ2sKv9iSd7gqYxrtZsORNcV4ZHkUkur5TuO+
            x6Bs14cUvtQyeiu41STt9wdvdd9pJQopDSApKmMtvfqUUlpnjiI0fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-17T06:40:53Z"
    mac: ENC[AES256_GCM,data:DmOu5B8N36zG+hlR27gjcHi+45pGg2WcfAck0xFDh8fbJGLFqoDZsnQjrmscwUa9vCUGRGSuzD8S2YK3dezRIa6caYItyIngDTODGN2X7oHBni2/XNSbC78XQ4/tr54EoGRe3iTciqYJWXHj7JnhmWTHQYAxPn/KZuYO9ViP2io=,iv:SCOl4sqbT+zLg/yCHEzDRfMF6quSv85o2baKRsxVv0c=,tag:3GGjF9oBF0PkP+FZI7hszQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
