apiVersion: v1
kind: Secret
metadata:
    name: z2m-secret
    namespace: home
type: Opaque
stringData:
    pan_id: ENC[AES256_GCM,data:qoLrSg==,iv:lFmBzsujDXEoqRfnikZi3tuSRfWbcNHx2KNYLkIWSq0=,tag:tsGwXPWO/9zlSs+D6D0Zcw==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwnsn3k525nltu06qtjhjrk37zffucrnygv6p6akdztjhlcm5qwqwqgpjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVnM3L1Zzak5yMjJ3MUxk
            Mk5HZFVkTGl5T2JwS0dNWHV6TlBkblFrenhZClU5azM1OC9qVkdmbXQzbCsycG1L
            ZndqUFBPNWJvRE9VeGRGaGRqLy9BYnMKLS0tIFE2MkdEYnVWSFkyYnRZZFo3QVh2
            eUM4WjZiaCtKYW9TRjZYYlU2MXhQZ2sKv9iSd7gqYxrtZsORNcV4ZHkUkur5TuO+
            x6Bs14cUvtQyeiu41STt9wdvdd9pJQopDSApKmMtvfqUUlpnjiI0fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-17T06:29:21Z"
    mac: ENC[AES256_GCM,data:JVzLYdZ2KEFG7ZAPpUBoijjrKKASqldJ8edG0Dmh6yaXYc19Bv4ph9PmPSoKI6JKaSSESK4VU5yYaOa2Jw24aUu1+ELyjie0e575jdigIzuKHBFRw4LySg59fQ2dodEXe52dAtsnGSAfeHg3S9iyhHErbs0kaCUok0FPtjAEspc=,iv:UwJuVxWfoqQ2AZMs5UD84aqfa7zCzhnXKk45HlFgUN8=,tag:T3eNsaoE6l8f4VDqprPHEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
