---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
  labels:
    k3s-upgrade: agent
spec:
  version: "v1.29.2+k3s1"
  serviceAccountName: system-upgrade
  concurrency: 2
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: DoesNotExist  
  prepare:
    image: rancher/k3s-upgrade
    args: [ "prepare", "k3s-server" ]
  upgrade:
    image: rancher/k3s-upgrade
