---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
  labels:
    k3s-upgrade: server
spec:
  version: "v1.31.12+k3s1"
  serviceAccountName: system-upgrade
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: In
      values:
      - "true"
  upgrade:
    image: rancher/k3s-upgrade
  tolerations:
    - key: "master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "master"
      operator: "Exists"
      effect: "NoExecute"
