---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
  labels:
    k3s-upgrade: server
spec:
  version: "v1.29.0+k3s1"
  serviceAccountName: system-upgrade
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - { key: k3s-upgrade, operator: Exists }
      - { key: k3s-upgrade, operator: NotIn, values: [ "disabled", "false" ] }
      - { key: node-role.kubernetes.io/master, operator: In, values: [ "true" ] }
  upgrade:
    image: rancher/k3s-upgrade
