---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app microbin
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      microbin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/danielszabo99/microbin
              tag: 2.0.4@sha256:c5bd4643135540a68a2846950fe4f65f3bcc94b62ed7c7644e563dfde6f1732c
            resources:
              requests:
                cpu: 5m
                memory: 50Mi
              limits:
                memory: 250Mi
            env:
              MICROBIN_PUBLIC_PATH: "https://p.${MAIN_DOMAIN}"
              MICROBIN_PORT: "80"
              MICROBIN_DATA_DIR: &data /var/lib/microbin
              MICROBIN_ADMIN_USERNAME: "${MICROBIN_ADMIN_USERNAME}"
              MICROBIN_ADMIN_PASSWORD: "${MICROBIN_ADMIN_PASSWORD}"
              MICROBIN_EDITABLE: "true"
              MICROBIN_HIDE_FOOTER: "true"
              MICROBIN_HIDE_HEADER: "true"
              MICROBIN_HIDE_LOGO: "true"
              MICROBIN_NO_LISTING: "true"
              MICROBIN_HIGHLIGHTSYNTAX: "true"
              MICROBIN_BIND: "0.0.0.0"
              MICROBIN_PRIVATE: "true"
              MICROBIN_PURE_HTML: "false"
              MICROBIN_JSON_DB: "false"
              MICROBIN_READONLY: "false"
              MICROBIN_SHOW_READ_STATS: "true"
              MICROBIN_THREADS: "1"
              MICROBIN_GC_DAYS: "90"
              MICROBIN_ENABLE_BURN_AFTER: "true"
              MICROBIN_DEFAULT_BURN_AFTER: "0"
              MICROBIN_WIDE: "true"
              MICROBIN_QR: "true"
              MICROBIN_ETERNAL_PASTA: "false"
              MICROBIN_ENABLE_READONLY: "true"
              MICROBIN_DEFAULT_EXPIRY: "24hour"
              MICROBIN_NO_FILE_UPLOAD: "false"
              MICROBIN_HASH_IDS: "false"
              MICROBIN_ENCRYPTION_CLIENT_SIDE: "true"
              MICROBIN_ENCRYPTION_SERVER_SIDE: "true"
              MICROBIN_MAX_FILE_SIZE_ENCRYPTED_MB: "8"
              MICROBIN_MAX_FILE_SIZE_UNENCRYPTED_MB: "8"
              MICROBIN_DISABLE_TELEMETRY: "true"
        pod:
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"
    service:
      app:
        controller: microbin
        ports:
          http:
            port: &port 80

    ingress:
      app:
        className: "nginx"
        hosts:
          - host: &host "p.${MAIN_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: microbin-config-v4
        globalMounts:
          - path: *data
