---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microbin-config-v4
  namespace: media
  labels:
    app.kubernetes.io/name: &name microbin
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client-bgp
