apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app modbus2x
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: mosquitto
      namespace: home
  values:
    controllers:
      modbus2x:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: vaizki/modbus2x
              tag: 75d196e
            env:
              TZ: "${TZ}"
              MODBUS_DEBUG: yes
              MODBUS_MQTT_BROKER: "${SVC_MQTT_ADDR}"
              MODBUS_MQTT_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: mosquitto-secret
                    key: username
              MODBUS_MQTT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: mosquitto-secret
                    key: password
              MODBUS_MQTT_PUBLISH_INTERVAL: 15
              MODBUS_HA_EXPIRE_AFTER: 35
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
        pod:
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      app:
        controller: modbus2x
        ports:
          http:
            port: 8080 # dummy port here

    persistence:
      config:
        enabled: true
        type: configMap
        name: modbus2x-config
        globalMounts:
          - path: /app/config.yml
            subPath: config.yml
