apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app modbus2x
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: mosquitto
      namespace: home
    #- name: csi-driver-nfs
    #  namespace: storage
  values:
    image:
      repository: vaizki/modbus2x
      tag: 75d196e
    env:
      TZ: "${TZ}"
      MODBUS_DEBUG: yes
      MODBUS_MQTT_BROKER: "${SVC_MQTT_ADDR}"
      MODBUS_MQTT_USERNAME:
        valueFrom:
          secretKeyRef:
            name: mosquitto-secret
            key: username
      MODBUS_MQTT_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: mosquitto-secret
            key: password
      MODBUS_MQTT_PUBLISH_INTERVAL: 15
      MODBUS_HA_EXPIRE_AFTER: 30

    service:
      main:
        ports:
          http:
            port: 8080 # dummy port here

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    persistence:
      #data:
      #  enabled: true
      #  mountPath: /data
      #  existingClaim: modbus2x-config-v1
      config:
        enabled: true
        type: configMap
        name: modbus2x-config
        mountPath: /app/config.yml
        subPath: config.yml

    tolerations:
      - key: "master"
        operator: "Equal"
        value: "false"
        effect: "NoSchedule"
