apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi-client-scanner
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      unifi-client-scanner:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: attley86/unifi-client-scanner
              pullPolicy: Always
              tag: main
            env:
              TZ: Europe/Helsinki
              CONTROLLER_URL: "${UCS_CONTROLLER_URL}"
              USERNAME: "${UCS_USERNAME}"
              PASSWORD: "${UCS_PASSWORD}"
              SITE_ID: "${UCS_SITE_ID}"
              EMAIL_SENDER: "${UCS_EMAIL_SENDER}"
              SMTP_USERNAME: "${UCS_SMTP_USERNAME}"
              SMTP_PASSWORD: "${UCS_SMTP_PASSWORD}"
              EMAIL_RECIPIENT: "${UCS_EMAIL_RECIPIENT}"
              SMTP_SERVER: "${UCS_SMTP_SERVER}"
              SMTP_PORT: 465
            probes:
              liveness: &probes
                enabled: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8080
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 4
              readiness: *probes
              startup:
                enabled: false
        pod:
          #nodeSelector:
          #  kubernetes.io/hostname: "k8s-worker2"
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      app:
        controller: unifi-client-scanner
        ports:
          http:
            port: *port
