apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi-client-scanner
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: unifi
      namespace: networking
  values:
    controllers:
      unifi-network-scanner:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: attley86/unifi-client-scanner
              tag: latest
            env:
              TZ: Europe/Helsinki
              CONTROLLER_URL: "${UCS_CONTROLLER_URL}"
              USERNAME: "${UCS_USERNAME}"
              PASSWORD: "${UCS_PASSWORD}"
              SITE_ID: "${UCS_SITE_ID}"
              EMAIL_SENDER: "${UCS_EMAIL_SENDER}"
              SMTP_USERNAME: "${UCS_SMTP_USERNAME}"
              SMTP_PASSWORD: "${UCS_SMTP_PASSWORD}"
              EMAIL_RECIPIENT: "${UCS_EMAIL_RECIPIENT}"
              SMTP_SERVER: "${UCS_SMTP_SERVER}"
              SMTP_PORT: 465
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
        pod:
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      app:
        controller: unifi-client-scanner
        ports:
          http:
            port: 8080 # health check port
