apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi-client-scanner
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: unifi
      namespace: networking
  values:
    controllers:
      unifi-network-scanner:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: attley86/unifi-client-scanner
              tag: latest
            env:
              TZ: Europe/Helsinki
              MODBUS_MQTT_BROKER: "${SVC_MQTT_ADDR}"
              MODBUS_MQTT_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: mosquitto-secret
                    key: username
              MODBUS_MQTT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: mosquitto-secret
                    key: password
              MODBUS_MQTT_PUBLISH_INTERVAL: 15
              MODBUS_HA_EXPIRE_AFTER: 35
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
        pod:
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      app:
        controller: unifi-client-scanner
        ports:
          http:
            port: 8080 # health check port
