---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  maxHistory: 3
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs2
      namespace: storage
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: public.ecr.aws/docker/library/eclipse-mosquitto
      tag: 2.0.18

    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${SVC_MQTT_ADDR}"
        externalTrafficPolicy: Local
        ipFamilyPolicy: "SingleStack"
        ipFamilies:
          - IPv4
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883

    persistence:
      data:
        enabled: true
        mountPath: /data
        existingClaim: mosquitto-config-v4
      config:
        enabled: true
        type: configMap
        name: mosquitto-config
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
      mosquitto-secret:
        enabled: true
        type: secret
        name: mosquitto-secret
        mountPath: /ext_mount/secret
        readOly: true

    tolerations:
      - key: "master"
        operator: "Equal"
        value: "false"
        effect: "NoSchedule"

    resources:
      requests:
        memory: 64M
      limits:
        memory: 64M
