---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 7m
  maxHistory: 3
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs2
      namespace: storage
  values:
    controllers:
      mosquitto:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.21
            resources:
              requests:
                memory: 64M
              limits:
                memory: 64M
                
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      app:
        controller: mosquitto
        type: LoadBalancer
        #annotations:
        #  metallb.universe.tf/loadBalancerIPs: "${SVC_MQTT_ADDR}"
        externalTrafficPolicy: Local
        ipFamilyPolicy: "SingleStack"
        ipFamilies:
          - IPv4
        ports:
          mqtt:
            enabled: true
            port: 1883

    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-config-v4
        globalMounts:
          - path: /data
      config:
        enabled: true
        type: configMap
        name: mosquitto-config
        globalMounts:
          - path: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
      mosquitto-secret:
        enabled: true
        type: secret
        name: mosquitto-secret
        globalMounts:
          - path: /ext_mount/secret
