---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-config-v4
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-client-bgp
