apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: home
type: Opaque
data:
    username: ENC[AES256_GCM,data:C88Kopz2,iv:pjEw3+oXqBZMLWj7OccIWIS8iZl4HjlLDabnopF7+CM=,tag:yUrVRntHegbNSlDNMeD95w==,type:str]
    password: ENC[AES256_GCM,data:6xdGjYBXjvA=,iv:NWtvT9IL20EzbMpIcAFU5sdNDMm8JYtGEz353TBgp3U=,tag:5BI971SXpfAMQTu3KlTW0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwnsn3k525nltu06qtjhjrk37zffucrnygv6p6akdztjhlcm5qwqwqgpjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVnM3L1Zzak5yMjJ3MUxk
            Mk5HZFVkTGl5T2JwS0dNWHV6TlBkblFrenhZClU5azM1OC9qVkdmbXQzbCsycG1L
            ZndqUFBPNWJvRE9VeGRGaGRqLy9BYnMKLS0tIFE2MkdEYnVWSFkyYnRZZFo3QVh2
            eUM4WjZiaCtKYW9TRjZYYlU2MXhQZ2sKv9iSd7gqYxrtZsORNcV4ZHkUkur5TuO+
            x6Bs14cUvtQyeiu41STt9wdvdd9pJQopDSApKmMtvfqUUlpnjiI0fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T15:55:51Z"
    mac: ENC[AES256_GCM,data:jjsBpcAD0c2vC9zfG4OwCSyL8rlYTb/ilvA/rzNlqXMbeVGgElhQc348e6jz+Y0t6tXRU/d+NlatdFSgPZHUIriRLPkV6tVrF9JsI/YgK5PkEra9ImDQ6xm2bp5lkf/zDar87SF6qr/LPTV6P0UyE14j7t8ZbRXcjIZcCSdGAJw=,iv:vnWqjaV33jJgJ8L7ZSkkrMNJsjgYIG9z39mdebzxgO8=,tag:hR5uqOSN+QJWvhDQXrxsWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
