apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: home
type: Opaque
data:
    username: ENC[AES256_GCM,data:C88Kopz2,iv:pjEw3+oXqBZMLWj7OccIWIS8iZl4HjlLDabnopF7+CM=,tag:yUrVRntHegbNSlDNMeD95w==,type:str]
    password: ENC[AES256_GCM,data:6xdGjYBXjvA=,iv:NWtvT9IL20EzbMpIcAFU5sdNDMm8JYtGEz353TBgp3U=,tag:5BI971SXpfAMQTu3KlTW0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwnsn3k525nltu06qtjhjrk37zffucrnygv6p6akdztjhlcm5qwqwqgpjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVnM3L1Zzak5yMjJ3MUxk
            Mk5HZFVkTGl5T2JwS0dNWHV6TlBkblFrenhZClU5azM1OC9qVkdmbXQzbCsycG1L
            ZndqUFBPNWJvRE9VeGRGaGRqLy9BYnMKLS0tIFE2MkdEYnVWSFkyYnRZZFo3QVh2
            eUM4WjZiaCtKYW9TRjZYYlU2MXhQZ2sKv9iSd7gqYxrtZsORNcV4ZHkUkur5TuO+
            x6Bs14cUvtQyeiu41STt9wdvdd9pJQopDSApKmMtvfqUUlpnjiI0fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T15:57:26Z"
    mac: ENC[AES256_GCM,data:XlPVvFwqiV25XM+se3RavCX2L1LkwvbS/fQ2YxaRoDYwe4VBwcdxmpbNTEK12M7+eMW2Ijs09KMj9BEz+OPEhO+27b6Utwyy2ZpQgQv5AuWPSWtKUfa4n2pcN3t0kXzpf74zepBgYp/TAW+1omSt9X8yFSVZ5fSsIGrYXBmIanU=,iv:3RYeC9nF6fU5D28uX0ItuhY1Z4uw1wVcQ8+YrQ9zoDg=,tag:6q+UPVIWoutmp2Se9Mw/8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
