apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: home
type: Opaque
stringData:
    mosquitto_pwd: ENC[AES256_GCM,data:5HcrHbm7PQzS7CtKMQyEga3PfMOerFRbLbiZESLi8HgU6QHalSm5dIW34mzOuZQ8Cx5nWJhpYap8lXxSSlZiMBJl8jMOQanxRyqu6v7F+Hnhs7BRiKtFTmH/KpSiEI92q3YVUfEWQQCzmgb4J9AjgY8X1g==,iv:y3FqBqIvxST/Pbt2fPfkuVPpVlu2fZIKEJI2j43McCU=,tag:6qFozyWaHfvm/tOdvEyGwg==,type:str]
    username: ENC[AES256_GCM,data:6OEPA9ZJ,iv:bL0puFOUfm42BJ9rWVP31FDKXGH5ZcoXA0Wykzekz34=,tag:EA88lKJS3GXkujTKDGd12Q==,type:str]
    password: ENC[AES256_GCM,data:JBRmumOJoU0=,iv:9J6ArYHIHU10/1VgnNPFnEj1w/qQKbROd3b+v8rnav0=,tag:kcYyXr85/Nod/Ybls/oRrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwnsn3k525nltu06qtjhjrk37zffucrnygv6p6akdztjhlcm5qwqwqgpjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVnM3L1Zzak5yMjJ3MUxk
            Mk5HZFVkTGl5T2JwS0dNWHV6TlBkblFrenhZClU5azM1OC9qVkdmbXQzbCsycG1L
            ZndqUFBPNWJvRE9VeGRGaGRqLy9BYnMKLS0tIFE2MkdEYnVWSFkyYnRZZFo3QVh2
            eUM4WjZiaCtKYW9TRjZYYlU2MXhQZ2sKv9iSd7gqYxrtZsORNcV4ZHkUkur5TuO+
            x6Bs14cUvtQyeiu41STt9wdvdd9pJQopDSApKmMtvfqUUlpnjiI0fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T16:05:32Z"
    mac: ENC[AES256_GCM,data:6mN/dE/+o8Pvn22E36NWidC/6g3Nhw9tkR56N/itPOtJHoPcPUyEg1PoPKaH2d5foYUGM2Hccah4P/FBllffnris63wWJSX0ffP6ZkJVXMO3NNHJn2MUF4N4E6WDzvrlNjCebVhtutekg+QkqcuojVv4AJcIJGVB4ykUgPIRrDU=,iv:B2NNVJmhQRD7Bot+ddu5LseE0OiFuktgvfOdg+DHTi8=,tag:P5+uBCU2kG2GiikjXG26IA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
