---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-config-v1
  namespace: finance
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client-bgp