---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app alertmanager-telegram
  namespace: monitoring
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      alertmanager:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              #repository: janwh/alertmanager-telegram
              #tag: latest
              repository: attley86/alertmanager-telegram
              tag: main
            env:
              - name: TELEGRAM_CHAT_ID
                valueFrom:
                  secretKeyRef:
                    name: telegram-alert-bot-secret
                    key: telegramChatId
              - name: TELEGRAM_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: telegram-alert-bot-secret
                    key: telegramToken
            resources:
              requests:
                cpu: 20m
                memory: 100Mi
        #pod:
        #  nodeSelector:
        #    kubernetes.io/arch: "arm64"
    service:
      app:
        controller: alertmanager
        ports:
          http:
            port: 8080

    nodeSelector:
      kubernetes.io/arch: amd64
