---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app alertmanager-telegram
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  test:
    enable: false
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    controllers:
      alertmanager:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: janwh/alertmanager-telegram
              tag: latest
            env:
              - name: TELEGRAM_CHAT_ID
                valueFrom:
                  secretKeyRef:
                    name: telegram-alert-bot-secret
                    key: telegramChatId
              - name: TELEGRAM_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: telegram-alert-bot-secret
                    key: telegramToken
            resources:
              requests:
                cpu: 20m
                memory: 100Mi
    service:
      app:
        controller: alertmanager
        ports:
          http:
            port: 8080
