---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app snmp-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: 5.3.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    image:
      repository: quay.io/prometheus/snmp-exporter
    serviceMonitor:
      enabled: true
      params:
        - name: switch
          auth: [public_v2]
          module:
            - if_mib
          target: 10.0.40.224
          interval: 1m
          scrapeTimeout: 1m
      path: /snmp
      scrapeTimeout: 10s
      relabelings:
        - action: labeldrop
          regex: (pod)
