---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lms
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 4
  uninstall:
    keepHistory: false
  values:
    controllers:
      lms:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: lmscommunity/lyrionmusicserver
              tag: 9.1.0
            resources:
              requests:
                memory: 255Mi
                cpu: 15m
              limits:
                memory: 4096Mi
        pod:
          # annotations:
          #   k8s.v1.cni.cncf.io/networks: |
          #     [{
          #       "name":"multus-mgmt",
          #       "namespace": "system",
          #       "ips": ["10.0.40.18/24"]
          #     }]
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"
    service:
      app:
        controller: lms
        ports:
          http:
            port: 9000
          cli:
            enabled: true
            port: 9090
            protocol: TCP
          slimproto:
            enabled: true
            port: 3483
            protocol: TCP
          slimproto-udp:
            enabled: true
            port: 3483
            protocol: UDP

    ingress:
      app:
        className: "nginx"
        hosts:
          - host: &host "lms.${MAIN_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: lms-config
