---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lms-net40-static
  namespace: media
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno1",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
           {
             "address": "10.0.40.81/24"
           }
         ]
      }
    }'
