---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    controllers:
      speedtest:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/miguelndecarvalho/speedtest-exporter
              tag: v3.5.4
            resources:
              requests:
                memory: 50M
              limits:
                memory: 100M
        pod:
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      app:
        controller: speedtest
        ports:
          metrics:
            enabled: true
            protocol: TCP
            port: 9798

    serviceMonitor:
      app:
        enabled: true
        endpoints:
          - interval: 60m
            path: /metrics
            port: metrics
            scrapeTimeout: 1m
