---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs2
      namespace: storage
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: esphome/esphome
              tag: 2023.12.9

            env:
              ESPHOME_INSTANCE_NAME: ESPHome
              ESPHOME_PORT: &port 6052
              ESPHOME_APPLICATION_URL: &host "esph.${MAIN_DOMAIN}"
              ESPHOME_LOG_LEVEL: info
              ESPHOME_DASHBOARD_USE_PING: true

            # App needs to run as root because of this: https://github.com/esphome/issues/issues/2752
            securityContext:
              runAsNonRoot: false
              readOnlyRootFilesystem: false
              privileged: true
              allowPrivilegeEscalation: true
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: esphome-static
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
          nginx.ingress.kubernetes.io/auth-realm: "Authentication required"
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: *host
            paths:
              - path: /
                name: main
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: esph-config-v4
