---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 35m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 4
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs2
      namespace: storage
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values:
                      - k8s-worker3

    controllers:
      esph:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: esphome/esphome
              tag: 2024.12.4

            env:
              ESPHOME_INSTANCE_NAME: ESPHome
              ESPHOME_PORT: &port 6052
              ESPHOME_APPLICATION_URL: &host "esph.${MAIN_DOMAIN}"
              ESPHOME_LOG_LEVEL: info
              ESPHOME_DASHBOARD_USE_PING: true

            # App needs to run as root because of this: https://github.com/esphome/issues/issues/2752
            securityContext:
              runAsNonRoot: false
              readOnlyRootFilesystem: false
              privileged: true
              allowPrivilegeEscalation: true
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-mgmt",
                "namespace": "system",
                "ips": ["10.0.40.17/24"]
              }]
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      app:
        controller: esph
        ports:
          http:
            port: *port

    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
          nginx.ingress.kubernetes.io/auth-realm: "Authentication required"
        className: "nginx"
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: esph-config-v4
      config-file-greeir:
        enabled: true
        type: configMap
        name: esph-greeir-configmap
        globalMounts:
          - path: /config/gree_ir1.h
            subPath: gree_ir1.h