---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: csi-driver-nfs2
      namespace: storage
  values:
    controllers:
      esph:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/esphome/esphome
              tag: 2025.10.1@sha256:85721eb16cbb9d68113ba3d805cf8bcd85ba7658bcbbeec8fb5c3708f40ce10c

            env:
              ESPHOME_INSTANCE_NAME: ESPHome
              ESPHOME_PORT: &port 6052
              ESPHOME_APPLICATION_URL: &host "esph.${MAIN_DOMAIN}"
              ESPHOME_DASHBOARD_USE_PING: true

            # App needs to run as root because of this: https://github.com/esphome/issues/issues/2752
            securityContext:
              runAsNonRoot: false
              readOnlyRootFilesystem: false
              privileged: true
              allowPrivilegeEscalation: true
        pod:
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      app:
        controller: esph
        ports:
          http:
            port: *port

    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
          nginx.ingress.kubernetes.io/auth-realm: "Authentication required"
        className: "nginx"
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: esph-config-v4
