---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esph-config-v2
  namespace: home
  labels:
    app.kubernetes.io/name: &name esph
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client-bgp
