apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    TZ: ENC[AES256_GCM,data:oj4EZzbdlzLi77RSX1d7,iv:nb3r9IYycUPboAm626SJ9TY+4hVPmv2dTFbOzcZ3qsM=,tag:DMHyURoZcxAKhYDlmfNoLQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:6D0FDrrSeFSQ9ZLPt88rNwNW,iv:b3m4GbzWtc7PFXWBMBHj5PGSaqjEuUH6Zz3EosLq6zE=,tag:JpREz271bVu1t/pcLqamsA==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:HiIoCPzOhjE=,iv:pxUrVOliMTeKmKia1iYeg85ArKop8685M2PdHq6t9sM=,tag:dWrOI1Dw7VjGKQkxNRQycw==,type:str]
    MAIN_DOMAIN: ENC[AES256_GCM,data:HgPtlt1eKMoc,iv:oz3aqrRAki/aGp6PCO9/ax2JS/16mrSR+ib+IEgDoJI=,tag:E66bl+k0sAurBzgnD3BQ3w==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:DKq+xwVbyUI=,iv:BV2aQXmQ0EPVRoBGDCtZKdJiI/L0LxqS7BtFCjNUxNs=,tag:x3cQf6UlU3rTbGitXeW85Q==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:gZewWnJwcJs=,iv:UNvNYojT0Bpm57l4IDRoyT0eGOvDfNa/KoTRGpdqx0A=,tag:hTPJmSfitlicvAFWtfJIaw==,type:str]
    SVC_HA_ADDR: ENC[AES256_GCM,data:45c4KIsf09PUs58=,iv:UDehBeKRuu4Q/AMuzQCijHb/hU0uuP+lYKvZK8MapQo=,tag:JGGuH3XayFsMz+Hhwf90Aw==,type:str]
    SVC_MQTT_ADDR: ENC[AES256_GCM,data:ELfiAhYkSGD2SFE=,iv:marNr8HETfMUvfM47EAhs2Kczr0NbvdDdmcOK8Jd9sw=,tag:38rHFMtvGavOnzTiCbb67w==,type:str]
    MLB_UNIFI_ADDR: ENC[AES256_GCM,data:/XLJoaW+bheSaDQ=,iv:GFQFtGV2nDQQjpfcKnmAcaCIGrhwKObDq/wyrPJrlsw=,tag:jknTtQyR5FS8Shk97Ag0JA==,type:str]
    MLB_SYSLOG_ADDR: ENC[AES256_GCM,data:2j5KmQbUReeQ/ys=,iv:NnvQ0F5Q3Rf9fm1JmPKdm8HQsz0X4S7d5YU7PPdf8cs=,tag:RKSi1B//CSbmPfcFF7Tqhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwnsn3k525nltu06qtjhjrk37zffucrnygv6p6akdztjhlcm5qwqwqgpjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVXkzNDVaQXFPMFd5T2Uv
            cDl2blM5RDJrNmVrNGJKVENjY3hsRGtPdFcwCjR1bjJBWVNZR3c5bnVUOUVNb0Nk
            WHZscmpHZDlFT1dlZG0vVllRb1ZsQjAKLS0tIE4xUDhZNzRlODZJZEFwYjZ0L2FP
            QWZjRWs4Y082YlZlT0VybjRLQ3owcVUKahKw3Z8xbqxffCKQlnXEy6fDZSyqUL0A
            5sy9iqG4QY9Rx7RrjrtvBnd84aDypQKXsECaehlwj+6FSnBCaOqihg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-18T14:19:37Z"
    mac: ENC[AES256_GCM,data:eFSw29KOUElsLRKRvCAVi6nqp1DBqOEjRsPBt2GDzGZ/IXsZDoq5nw/RI6scNhgiH8k3d9BZRjmkrkOyslSenfQx7s6leZYiVITEQqpNClSWF5nQV+FoDvzEI2eHxbHOA5c6FRfkMDVVAWZhbFFAWXCtHkUbCMjNzbFkdp5zT0s=,iv:f+AjmbLyo1DWdS03zqrraIQ+T6wuFsYjjMo67Jj/UP8=,tag:8cJZYWJRfAyXmfKuCvThvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
