apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    TZ: ENC[AES256_GCM,data:oj4EZzbdlzLi77RSX1d7,iv:nb3r9IYycUPboAm626SJ9TY+4hVPmv2dTFbOzcZ3qsM=,tag:DMHyURoZcxAKhYDlmfNoLQ==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:6D0FDrrSeFSQ9ZLPt88rNwNW,iv:b3m4GbzWtc7PFXWBMBHj5PGSaqjEuUH6Zz3EosLq6zE=,tag:JpREz271bVu1t/pcLqamsA==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:HiIoCPzOhjE=,iv:pxUrVOliMTeKmKia1iYeg85ArKop8685M2PdHq6t9sM=,tag:dWrOI1Dw7VjGKQkxNRQycw==,type:str]
    MAIN_DOMAIN: ENC[AES256_GCM,data:HgPtlt1eKMoc,iv:oz3aqrRAki/aGp6PCO9/ax2JS/16mrSR+ib+IEgDoJI=,tag:E66bl+k0sAurBzgnD3BQ3w==,type:str]
    MQTT_USERNAME: ENC[AES256_GCM,data:KZcdVtmz,iv:BG93n61aDDLz3ETYEBFYVPVqrD+I6O+WwpUq7wBIAis=,tag:FkkbSOmvGcbq/Jnzaa/Vfg==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:3DXTSlj+S7k=,iv:QJ2n53d0UvCpvukUJK3M05ep+evYLKpHP2Tk0F8SR/o=,tag:6WU8npiQM/UYzaCyD6L1uA==,type:str]
    INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:DKq+xwVbyUI=,iv:BV2aQXmQ0EPVRoBGDCtZKdJiI/L0LxqS7BtFCjNUxNs=,tag:x3cQf6UlU3rTbGitXeW85Q==,type:str]
    INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:gZewWnJwcJs=,iv:UNvNYojT0Bpm57l4IDRoyT0eGOvDfNa/KoTRGpdqx0A=,tag:hTPJmSfitlicvAFWtfJIaw==,type:str]
    CAMERA_USERNAME: ENC[AES256_GCM,data:YodKlSE=,iv:muFYYs44yFWU1wS8AaoXCKsLgUpbi7+fafSf+lbRsI4=,tag:ZOiyDAbi1YOqkjbYCPGvxg==,type:str]
    CAMERA_PASSWORD: ENC[AES256_GCM,data:T55Bw4eTQVY=,iv:FjLeBRX6bbDJjJwkrGhq7+VRCjE69bpooW0bhJx4Kqk=,tag:HKPTR0VkiWcZl0DN1ClY8Q==,type:str]
    CAMERA_ETUOVI_IP: ENC[AES256_GCM,data:xsU8bzCuL7NdQfo=,iv:XWlj9kPdAgVmvtdvcCRmHt5x6KcCEMWFU4ef35FvlIg=,tag:xeSHZok0tw0McMDOCr/XeQ==,type:str]
    CAMERA_TERASSI_IP: ENC[AES256_GCM,data:BrcNmGFDqMJw9ek=,iv:SBhMjXRE/EmRzvO7xh1S7HSHpLVQij3NPDbTvy6tI7s=,tag:qeYUWp0bU6RXnk/W/lVzWg==,type:str]
    CAMERA_TAKAOVI_IP: ENC[AES256_GCM,data:rxF+x4M3YtkWnmE=,iv:C7IXwkRI5IePPtWZYBtMaaDmWEAPmz9nTxhuImIvIts=,tag:R+C+IQCKzISCZVXZ+qDFWQ==,type:str]
    SVC_HA_ADDR: ENC[AES256_GCM,data:45c4KIsf09PUs58=,iv:UDehBeKRuu4Q/AMuzQCijHb/hU0uuP+lYKvZK8MapQo=,tag:JGGuH3XayFsMz+Hhwf90Aw==,type:str]
    SVC_MQTT_ADDR: ENC[AES256_GCM,data:ELfiAhYkSGD2SFE=,iv:marNr8HETfMUvfM47EAhs2Kczr0NbvdDdmcOK8Jd9sw=,tag:38rHFMtvGavOnzTiCbb67w==,type:str]
    MLB_UNIFI_ADDR: ENC[AES256_GCM,data:/XLJoaW+bheSaDQ=,iv:GFQFtGV2nDQQjpfcKnmAcaCIGrhwKObDq/wyrPJrlsw=,tag:jknTtQyR5FS8Shk97Ag0JA==,type:str]
    MLB_SYSLOG_ADDR: ENC[AES256_GCM,data:2j5KmQbUReeQ/ys=,iv:NnvQ0F5Q3Rf9fm1JmPKdm8HQsz0X4S7d5YU7PPdf8cs=,tag:RKSi1B//CSbmPfcFF7Tqhw==,type:str]
    MICROBIN_ADMIN_USERNAME: ENC[AES256_GCM,data:dcuQB0Q=,iv:rOYWan2TRm9G++PGGJi23fFFNjUjLt5G9ASYsx+kQ6k=,tag:FWoBb6fkiHVl1NLlIxbTIA==,type:str]
    MICROBIN_ADMIN_PASSWORD: ENC[AES256_GCM,data:ZOnk2tyPWqs=,iv:Q+VOvrs1rrrk6t43XmFk1DHHnukkc/o0mG3PqlTlJsA=,tag:8d4dmxJ+NLWw5LFeeSbE6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwnsn3k525nltu06qtjhjrk37zffucrnygv6p6akdztjhlcm5qwqwqgpjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVXkzNDVaQXFPMFd5T2Uv
            cDl2blM5RDJrNmVrNGJKVENjY3hsRGtPdFcwCjR1bjJBWVNZR3c5bnVUOUVNb0Nk
            WHZscmpHZDlFT1dlZG0vVllRb1ZsQjAKLS0tIE4xUDhZNzRlODZJZEFwYjZ0L2FP
            QWZjRWs4Y082YlZlT0VybjRLQ3owcVUKahKw3Z8xbqxffCKQlnXEy6fDZSyqUL0A
            5sy9iqG4QY9Rx7RrjrtvBnd84aDypQKXsECaehlwj+6FSnBCaOqihg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-01T09:10:18Z"
    mac: ENC[AES256_GCM,data:0PsbRmPUFMDcOsJdB/xj9mPYNwedXIvk3XKwVyqGQvQfu/mMt8PoxzrA9Bc4Lc8Mv8CuOHg+DQEMutUjJRXULJL8MSUTLNMn+wB8jhsP8Pk3yFYDHG0ZNWZYO1pbv86nQhAfSf2syAzTMr3ZBNabyjfbrmiHQ4X7zQw3lAb82OQ=,iv:LejtCeqylljcgrzgX7s7jin9JGO3YKeA3GOXgRObqFQ=,tag:JwVndVA3uYBolsoYCICnEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
