---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oatel.net
  namespace: networking
spec:
  secretName: oatel.net-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 384
  commonName: "oatel.net"
  dnsNames:
  - "oatel.net"
  - "*.oatel.net"
