---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wyoming-piper
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs2
      namespace: storage
  values:
    controllers:
      piper:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: rhasspy/wyoming-piper
              tag: 1.5.0
            args:
              - --voice
              - fi_FI-harri-medium
            probes: &probes
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 500Mi 

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      app:
        controller: piper
        ports:
          http:
            port: 10200
            protocol: TCP

    persistence:
      data:
        enabled: true
        existingClaim: wyoming-piper
        globalMounts:
          - path: /data
