---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wyoming-piper
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client-bgp
