---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hass
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs2
      namespace: storage
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.4.2
            probes: &probes
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
          code:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.23.1
            env:
              TZ: Europe/Helsinki
            workingDir: /config
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
            probes: *probes

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: hass-static
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      main:
        ports:
          http:
            port: 8123
          code:
            port: 8080

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        hosts:
          - host: &host "hass.${MAIN_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
      code:
        enabled: true
        className: nginx
        hosts:
          - host: &code-host "hasscode.${MAIN_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: code
        tls:
          - hosts:
              - *code-host


    persistence:
      config:
        enabled: true
        existingClaim: hass-config-v4
        advancedMounts:
          main:
            main:
              - path: /config
            code:
              - path: /config
