---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  maxHistory: 3
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs
      namespace: storage
  values:
    global:
      fullnameOverride: hass
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.9.1

    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${SVC_HA_ADDR}"
        externalTrafficPolicy: Local
        ipFamilyPolicy: "SingleStack"
        ipFamilies:
          - IPv4
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: &host "hass.${MAIN_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    
    persistence:
      config:
        enabled: true
        existingClaim: hass-config-v1

    tolerations:
      - key: "master"
        operator: "Equal"
        value: "false"
        effect: "NoSchedule"

    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.11.0
        env:
          TZ: Europe/Helsinki
        workingDir: /config
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "nginx"
          hosts:
            - host: &code-host "hasscode.${MAIN_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *code-host

        volumeMounts:
          - name: config
            mountPath: /config
