---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hass
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs2
      namespace: storage
  values:
    controllers:
      hass:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.11.1
            probes: &probes
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
          code:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.95.2
            env:
              TZ: Europe/Helsinki
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false
            workingDir: /config
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - "/config"
            probes: *probes

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: hass-static-40
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      app:
        controller: hass
        ports:
          http:
            port: 8123
      code:
        controller: hass
        ports:
          code:
            port: 8080

    ingress:
      app:
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        hosts:
          - host: &host "hass.${MAIN_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
      code:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
          nginx.ingress.kubernetes.io/auth-realm: "Authentication required"
        className: nginx
        hosts:
          - host: &code-host "hasscode.${MAIN_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: code
                  port: code
        tls:
          - hosts:
              - *code-host


    persistence:
      config:
        enabled: true
        existingClaim: hass-config-v4
        globalMounts:
          - path: /config
