---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: hass-static-20
  namespace: home
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "br0.20",
      "mode": "bridge",
      "vlan": 20,
      "capabilities": {
            "ips": true
          },
      "ipam": {
        "type": "static",
        "addresses": [
           {
             "address": "10.0.20.15/24"
           }
         ]
      }
    }'
