---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-config-v4
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client-bgp
