---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app firefly
  namespace: finance
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/fireflyiii/core
              tag: version-6.2.7@sha256:dc78dac2d3db78665e17c89f5075602ec8f7c84d10610a7888e633b83334a340
            env: &env
              TZ: "${TZ}"
              APP_ENV: "production"
              APP_DEBUG: "false"
              LOG_CHANNEL: "stdout"
              APP_LOG_LEVEL: "notice"
              AUDIT_LOG_LEVEL: "info"
              DEFAULT_LANGUAGE: "en_GB"
              DEFAULT_LOCALE: "equal"
              APP_URL: "https://firefly.${MAIN_DOMAIN}"
              TRUSTED_PROXIES: "*"
              COOKIE_PATH: "/"
              COOKIE_DOMAIN: "firefly.${MAIN_DOMAIN}"
              COOKIE_SECURE: "true"
              COOKIE_SAMESITE: "lax"
              DISABLE_FRAME_HEADER: "false"
              DISABLE_CSP_HEADER: "false"
              TRACKER_SITE_ID: ""
              TRACKER_URL: ""
              DB_CONNECTION: "pgsql"
              DB_HOST: ${PGSQL_SERVER}
              DB_PORT: "5432"
              DB_DATABASE: *app
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: *app
                    key: DB_USERNAME
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: *app
                    key: DB_PASSWORD
              APP_KEY:
                valueFrom:
                  secretKeyRef:
                    name: *app
                    key: APP_KEY
              SEND_ERROR_MESSAGE: "false"
              SEND_REPORT_JOURNALS: "false"
              ENABLE_EXCHANGE_RATES: "true"
              ENABLE_EXTERNAL_RATES: "true"
              ALLOW_WEBHOOKS: "false"
            securityContext: &sc
              allowPrivilegeEscalation: false
              capabilities:
                drop: [ "ALL" ]
            resources:
              requests:
                cpu: "10m"
                memory: "100Mi"
              limits:
                cpu: "1"
                memory: "512Mi"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
        pod:
          nodeSelector:
            kubernetes.io/hostname: "k8s-worker6"
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      *app :
        forceRename: *app
        controller: *app
        ports:
          http:
            port: 80
            targetPort: 8080
            protocol: HTTP
            appProtocol: http

    ingress:
      app:
        className: nginx
        hosts:
          - host: &host "firefly.${MAIN_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: *app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /mnt/data/firefly
        hostPathType: DirectoryOrCreate
        advancedMounts:
          firefly:
            main:
              - subPath: upload
                path: /var/www/html/storage/upload