---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: vmnet-router-v4
  namespace: metallb-system
spec:
  holdTime: 1m30s
  myASN: 64512
  peerASN: 64512
  peerAddress: 10.0.40.1
  peerPort: 179
  # https://github.com/metallb/metallb/issues/1537
  ebgpMultiHop: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ipv4
  namespace: metallb-system
spec:
  addresses:
    - 10.0.88.0/24
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-other
  namespace: metallb-system
spec:
  ipAddressPools:
  - ipv4
  aggregationLength: 32
