---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 15m
  chart:
    spec:
      chart: metallb
      version: 0.14.8
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      logLevel: warn
    speaker:
      tolerateMaster: true
      logLevel: warn
      frr:
        enabled: true
        image:
          repository: docker.io/frrouting/frr
          tag: v8.4.1
          #tag: v8.4.0
    crds:
      enabled: true
