apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-configmap
  namespace: home
data:
  config.yml: |
    logger:
      default: info
      # logs:
      #   frigate.record: debug
    
    mqtt:
      host: "${SVC_MQTT_ADDR}"
      topic_prefix: frigate
      user: "${MQTT_USERNAME}"
      password: "${MQTT_PASSWORD}"
    
    database:
      path: /data/frigate.db
    
    detectors:
      coral:
        type: edgetpu
        device: usb
    
    ffmpeg:
      global_args: ["-hide_banner", "-loglevel", "warning"]
      hwaccel_args: ["-hwaccel", "vaapi", "-hwaccel_device", "/dev/dri/renderD128", "-hwaccel_output_format", "yuv420p"]
    
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    
    record:
      enabled: true
      retain:
        days: 30
        mode: all
      events:
        retain:
          default: 30
          mode: active_objects
    
    objects:
      # Optional: list of objects to track from labelmap
      track:
        - person
        - cat
        - dog
        - bird
      filters:
      # Generate filters from: Webui->Camera->Debug->Mask&ZoneCreator->Add
        cat:
          threshold: 0.70
          min_score: 0.6
          mask:
            - 132,499,273,537,282,720,0,720,0,605,0,470
            - 447,0,195,87,260,164,417,154
        dog:
          threshold: 0.70
          min_score: 0.6
          mask:
            - 132,499,273,537,282,720,0,720,0,605,0,470
            - 447,0,195,87,260,164,417,154
        person:
          threshold: 0.8
          min_score: 0.6
          min_area: 5000
          max_area: 100000
    
    go2rtc:
      streams:
        frigate_etuovi_main: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_ETUOVI_IP}:554/h264Preview_01_main"
        frigate_etuovi_sub: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_ETUOVI_IP}:554/h264Preview_01_sub"
        frigate_terassi_main: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_TERASSI_IP}:554/h264Preview_01_main"
        frigate_terassi_sub: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_TERASSI_IP}:554/h264Preview_01_sub"
        frigate_takaovi_main: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_TAKAOVI_IP}:554/h264Preview_01_main"
        frigate_takaovi_sub: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_TAKAOVI_IP}:554/h264Preview_01_sub"
        frigate_tuulietu_main: "rtsp://${CAMERA_TUULI_USERNAME}:${CAMERA_TUULI_PASSWORD}@${CAMERA_TUULIETU_IP}:554/h264Preview_01_main"
        frigate_tuulietu_sub: "rtsp://${CAMERA_TUULI_USERNAME}:${CAMERA_TUULI_PASSWORD}@${CAMERA_TUULIETU_IP}:554/h264Preview_01_sub"
    
    cameras:
      frigate_etuovi:
        ffmpeg:
          inputs:
            - path: rtsp://localhost:8554/frigate_etuovi_sub
              roles: ["detect"]
            - path: rtsp://localhost:8554/frigate_etuovi_main
              roles: ["record"]
        detect:
          width: 1280
          height: 720
          fps: 10
      frigate_terassi:
        ffmpeg:
          inputs:
            - path: rtsp://localhost:8554/frigate_terassi_sub
              roles: ["detect"]
            - path: rtsp://localhost:8554/frigate_terassi_main
              roles: ["record"]
        detect:
          width: 1280
          height: 720
          fps: 10
      frigate_takaovi:
        ffmpeg:
          inputs:
            - path: rtsp://localhost:8554/frigate_takaovi_sub
              roles: ["detect"]
            - path: rtsp://localhost:8554/frigate_takaovi_main
              roles: ["record"]
        detect:
          width: 1280
          height: 720
          fps: 10
      frigate_tuulietu:
        ffmpeg:
          inputs:
            - path: rtsp://localhost:8554/frigate_tuulietu_sub
              roles: ["detect", "record"]
        objects:
          track:
            - person
            - cat
            - dog
            - car
            - motorcycle
        record:
          enabled: true
          retain:
            days: 14
            mode: all
          events:
            retain:
              default: 14
              mode: active_objects
        detect:
          width: 1280
          height: 720
          fps: 10
