apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-configmap
  namespace: home
data:
  config.yml: |
    logger:
      default: info   
    mqtt:
      host: "${SVC_MQTT_ADDR}"
      topic_prefix: frigate
      user: "${MQTT_USERNAME}"
      password: "${MQTT_PASSWORD}"
    
    database:
      path: /data/frigate.db
    
    detectors:
      coral:
        type: edgetpu
        device: usb
    
    ffmpeg:
      global_args: ["-hide_banner", "-loglevel", "warning"]
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 30
    
    detect:
      enabled: true
    
    record:
      enabled: true
      retain:
        days: 7
        mode: all
      alerts:
        retain:
          days: 30
          mode: active_objects
      detections:
        retain:
          days: 30
          mode: active_objects
    
    objects:
      # Optional: list of objects to track from labelmap
      track:
        - person
        - car
      filters:
        person:
          threshold: 0.8
          min_score: 0.6
          min_area: 5000
          max_area: 100000
        car:
          threshold: 0.8
          min_score: 0.6
          min_area: 5000
          max_area: 100000
    
    go2rtc:
      streams:
        frigate_varasto_main: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_VARASTO_IP}:554/ch0_0.h264"
        frigate_varasto_sub: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_VARASTO_IP}:554/ch0_1.h264"
        frigate_etuovi_main: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_ETUOVI_IP}:554/h264Preview_01_main"
        frigate_etuovi_sub: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_ETUOVI_IP}:554/h264Preview_01_sub"
        frigate_etupiha_main: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_ETUPIHA_IP}:554/h264Preview_01_main"
        frigate_etupiha_sub: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_ETUPIHA_IP}:554/h264Preview_01_sub"
        frigate_terassi_main: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_TERASSI_IP}:554/h264Preview_01_main"
        frigate_terassi_sub: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_TERASSI_IP}:554/h264Preview_01_sub"
        frigate_takaovi_main: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_TAKAOVI_IP}:554/h264Preview_01_main"
        frigate_takaovi_sub: "rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_TAKAOVI_IP}:554/h264Preview_01_sub"
 
    cameras:
      frigate_varasto:
        ffmpeg:
          inputs:
            - path: rtsp://localhost:8554/frigate_varasto_sub
              roles: ["detect"]
            - path: rtsp://localhost:8554/frigate_varasto_main
              roles: ["record"]
        detect:
          width: 1280
          height: 720
          fps: 2
          max_disappeared: 40
        record:
          enabled: false
      frigate_etuovi:
        ffmpeg:
          inputs:
            - path: rtsp://localhost:8554/frigate_etuovi_sub
              roles: ["detect"]
            - path: rtsp://localhost:8554/frigate_etuovi_main
              roles: ["record"]
        detect:
          width: 1280
          height: 720
          fps: 5
          max_disappeared: 40
      frigate_etupiha:
        ffmpeg:
          inputs:
            - path: rtsp://localhost:8554/frigate_etupiha_sub
              roles: ["detect"]
            - path: rtsp://localhost:8554/frigate_etupiha_main
              roles: ["record"]
        objects:
          track:
            - person
            - car
        detect:
          width: 1280
          height: 720
          fps: 5
          max_disappeared: 40
      frigate_terassi:
        ffmpeg:
          inputs:
            - path: rtsp://localhost:8554/frigate_terassi_sub
              roles: ["detect"]
            - path: rtsp://localhost:8554/frigate_terassi_main
              roles: ["record"]
        detect:
          width: 1280
          height: 720
          fps: 5
          max_disappeared: 40
        record:
          enabled: true
          retain:
            days: 14
            mode: motion
      frigate_takaovi:
        ffmpeg:
          inputs:
            - path: rtsp://localhost:8554/frigate_takaovi_sub
              roles: ["detect"]
            - path: rtsp://localhost:8554/frigate_takaovi_main
              roles: ["record"]
        detect:
          width: 1280
          height: 720
          fps: 5
          max_disappeared: 40
        record:
          enabled: true
          retain:
            days: 14
            mode: motion