---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - helm-release.yaml
configMapGenerator:
  - name: frigate-configmap
    namespace: home
    files:
      - config.yml=./resources/config.yml
generatorOptions:
  disableNameSuffixHash: true
