---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-dedicated-media
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-frigate-dedicated-bgp
