---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lms-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client-bgp
