---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syslog
  namespace: monitoring
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      syslog:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/syslog-ng
              tag: 4.8.3
              pullPolicy: IfNotPresent
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                memory: 50M
              limits:
                memory: 100M
        pod:
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"
      
    service:
      app:
        controller: syslog
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${MLB_SYSLOG_ADDR}"
        ports:
          syslog:
            enabled: true
            port: 5514
            protocol: UDP

    persistence:
      config:
        enabled: true
        existingClaim: syslog-config-v4
        globalMounts:
          - path: "/config"
