---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syslog-config-v4
  namespace: monitoring
  labels:
    app.kubernetes.io/name: &name syslog
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client-bgp
