---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: charts
  namespace: flux-system
spec:
  interval: 12m
  path: ./cluster/flux/charts
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
