---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    image:
      repository: bitnami/influxdb
      tag: 2.7.1
      pullPolicy: IfNotPresent

    service:
      main:
        ports:
          http:
            port: 8086

    persistence:
      config:
        enabled: true
        existingClaim: influxdb-config-v1
        mountPath: /var/lib/influxdb

    tolerations:
      - key: "master"
        operator: "Equal"
        value: "false"
        effect: "NoSchedule"

    resources:
      limits:
        cpu: 8000m
        memory: 4096Mi
      requests:
        cpu: 250m
        memory: 512Mi
