---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      influxdb:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: bitnami/influxdb
              #tag: 3.0.3
              tag: 2.7.11
              pullPolicy: IfNotPresent
            env:
              INFLUXDB_ADMIN_USER_PASSWORD: "${INFLUXDB_ADMIN_USER_PASSWORD}"
              INFLUXDB_ADMIN_USER_TOKEN: "${INFLUXDB_ADMIN_USER_TOKEN}"
              INFLUXDB_NODE_ID: "${INFLUXDB_NODE_ID}"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              limits:
                cpu: 8000m
                memory: 4096Mi
              requests:
                cpu: 250m
                memory: 512Mi
        pod:
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      app:
        controller: influxdb
        ports:
          http:
            port: 8086

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        enabled: true
        className: nginx
        hosts:
          - host: &host "influx.${MAIN_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: influxdb-config-v4
        globalMounts:
          - path: /var/lib/influxdb
