---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: bitnami/influxdb
      tag: 1.8.5
      pullPolicy: IfNotPresent
    env:
      INFLUXDB_ADMIN_USER_PASSWORD: "${INFLUXDB_ADMIN_USER_PASSWORD}"
      INFLUXDB_ADMIN_USER_TOKEN: "${INFLUXDB_ADMIN_USER_TOKEN}"

    service:
      main:
        ports:
          http:
            port: 8086

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "influx.${MAIN_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: influxdb-config-v4
        mountPath: /var/lib/influxdb

    tolerations:
      - key: "master"
        operator: "Equal"
        value: "false"
        effect: "NoSchedule"

    resources:
      limits:
        cpu: 8000m
        memory: 4096Mi
      requests:
        cpu: 250m
        memory: 512Mi
