---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-config-v1
  namespace: monitoring
  labels:
    app.kubernetes.io/name: &name influxdb
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
