---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app echo-server
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            replicas: 2
            strategy: RollingUpdate
            annotations:
              reloader.stakater.com/auto: "true"
            replicas: 3
            strategy: RollingUpdate
            image:
              repository: docker.io/jmalloc/echo-server
              tag: 0.3.6
            env:
              PORT: &port 8080
              LOG_WITHOUT_NEWLINE: true
              LOG_IGNORE_PATH: &path /health
              PROMETHEUS_ENABLED: true
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: *path
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            tolerations:
               - key: "master"
                 operator: "Equal"
                 value: "false"
                 effect: "NoSchedule"
             resources:
               requests:
                 cpu: 5m
                 memory: 10Mi
               limits:
                 memory: 50Mi

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app

    service:
      main:
        ports:
          http:
            port: &port 8080

    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "echo.${MAIN_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    
