---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.13.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    controller:
      replicaCount: 2
      config:
        hsts: false
        ssl-prefer-server-ciphers: false
        ssl-protocols: "TLSv1.3 TLSv1.2"
        ssl-redirect: false
        server-tokens: false
        enable-real-ip: true
        enable-brotli: "true"
        custom-http-errors: 404,403
      use-forwarded-headers: "true"
      service:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: 10.0.88.111
        externalTrafficPolicy: Local
        ipFamilyPolicy: "SingleStack"
        ipFamilies:
          - IPv4
      publishService:
        enabled: false

      metrics:
        enabled: true
        prometheusRule:
          enabled: false
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
              app.kubernetes.io/component: controller
      extraArgs:
        default-ssl-certificate: "networking/oatel.net-tls"
      resources:
        limits:
          cpu: 2281m
          memory: 524M
