---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multus
  namespace: system
spec:
  interval: 5m
  chart:
    spec:
      chart: multus
      version: 5.0.4
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.0.2-thick

    cni:
      image:
        repository: ghcr.io/angelnu/cni-plugins
        tag: 1.3.0
