---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multus
  namespace: system
spec:
  interval: 5m
  chart:
    spec:
      chart: multus
      version: 5.0.3
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.0.0-alpha

    args:
      - --multus-conf-file=auto
      - --cni-version=0.3.1
      - --multus-kubeconfig-file-host=/var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig

    tolerations:
      - key: "master"
        operator: "Equal"
        value: "false"
        effect: "NoSchedule"

    cni:
      image:
        repository: ghcr.io/onedr0p/cni-plugins
        tag: "1.3.0"

      paths:
        configDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
        binDir: /var/lib/rancher/k3s/data/current/bin

      version: "0.3.1"
