---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: multus
  namespace: system
spec:
  interval: 5m
  chart:
    spec:
      chart: multus
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v3.9.3
    args:
      - --multus-conf-file=auto

    cni:
      image:
        repository: ghcr.io/angelnu/cni-plugins
        tag: 1.4.0
      paths:
        config: /etc/cni/net.d
        bin: /opt/cni/bin
