apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nodered
  namespace: home
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      nodered:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/k8s-at-home/node-red
              tag: v3.0.2
            env:
              TZ: "${TZ}"
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              fsGroup: 568
              fsGroupChangePolicy: "OnRootMismatch"
            resources:
              requests:
                memory: 64M
              limits:
                memory: 1Gi
        pod:
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"


    service:
      app:
        controller: nodered
        ports:
          http:
            port: 1880

    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
          nginx.ingress.kubernetes.io/auth-realm: "Authentication required"
        className: nginx
        hosts:
          - host: &host "noder.${MAIN_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app

        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: nodered-config-v4
        globalMounts:
          - path: "/data"
