---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-config-v1
  namespace: home
  labels:
    app.kubernetes.io/name: &name nodered
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
